name: Filesystem Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy:
    uses: Project-Arrakis/.github/.github/workflows/reusable-security-scan.yml@main
    with:
      run-gitleaks: false
      run-semgrep: false
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
