name: Filesystem Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy:
    uses: Project-Arrakis/.github/.github/workflows/reusable-security-scan.yml@feat/reusable-security-scan-workflow
    with:
      run-gitleaks: false
      run-semgrep: false
    secrets: inherit
