name: Secret Scan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: Project-Arrakis/.github/.github/workflows/reusable-security-scan.yml@feat/reusable-security-scan-workflow
    with:
      run-semgrep: false
      run-trivy: false
    secrets: inherit
